version: '3'
services:
  conso_score_postgresql:
    container_name: conso_score_postgresql
    image: postgres
    restart: always
    expose:
      - 5432
    ports:
      - 15432:5432
    volumes:
      - ./database:/var/lib/postgresql/dev/database/conso-score
      - ./database/set_up_db.sh:/docker-entrypoint-initdb.d/1-set_up_db.sh:ro
    environment:
      POSTGRES_PASSWORD: example
